project:
  type: website
  output-dir: docs

website:
  title: "STAT-515 Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: projects/gold-reserves.qmd
            text: Midterm Redesign Gold Reserves
          - href: projects/gold-reserves-code.qmd
            text: Midterm Redesign Code Overview
          - href: projects/image-selection.qmd
            text: Mit Project Image Selection
          # - href: projects/final-project.qmd
          #   text: Final project
          - href: projects/instructions.qmd
            text: new project instructions
      - about.qmd
      - stat-515.qmd
      # Add additional projects...
      # Create projects/my-project.qmd with a YAML header (title, optional description) and your content/code.
      # Then extend the navbar list with a new entry like below
      # - href: projects/my-project.qmd
      #   text: My Project Title

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true



