---
title: "STAT-515"
#image: "https://avatars.githubusercontent.com/u/47530196?v=4&size=250"
about: 
  id: Jonathan-Dale
  template: jolla
  image-shape: rounded
  image-width: 15em
  links:
    - text: Email
      icon: envelope
      href: mailto:jdale7@gmu.edu
    - text: GitHub
      icon: github
      href: https://github.com/jonathan-dale
    - text: YouTube
      icon: youtube
      href: https://youtube.com/@jonathan-dale

---

### Welcome to STAT-515!

This course dives into the art and science of understanding data, its all about exploring how data tells a story. Importantly how a good visual can make that story more clear, sharper, and more impact. Through the semester, we dive into hands on modeling bringing data to life with R to find and uncover the patterns hidden in complex data sets.

The [midterm project](projects/gold-reserves.qmd) is a creative challenge blending design with statistical insight. It focuses on redesigning data visualizations using ggplot2 in R, a critical component of the course that will guide us through practical analysis and visualization. 

Later in the course the modeling and visualization skills come together in the [final-project](projects/final.qmd) where real-world data is used to build predictive models while crafting intuitive visuals that make the results memorable. 

<!-- ## Quick Navigation

- [Projects](projects/mining-analysis.qmd) - Explore data analysis projects
- [About](about.qmd) - Learn more about this course -->

---

*Click on "Projects" in the navigation menu above to view all course projects.*
